/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramIsAdminRouteImport } from './routes/api/public/telegram/is-admin'
import { Route as ApiPublicTelegramSessionRouteImport } from './routes/api/public/telegram/session'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramVerifyAccessRouteImport } from './routes/api/public/telegram/verify-access'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramImageNameRouteImport } from './routes/api/public/telegram/image/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramIsAdminRoute =
  ApiPublicTelegramIsAdminRouteImport.update({
    id: '/api/public/telegram/is-admin',
    path: '/api/public/telegram/is-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSessionRoute =
  ApiPublicTelegramSessionRouteImport.update({
    id: '/api/public/telegram/session',
    path: '/api/public/telegram/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramVerifyAccessRoute =
  ApiPublicTelegramVerifyAccessRouteImport.update({
    id: '/api/public/telegram/verify-access',
    path: '/api/public/telegram/verify-access',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramImageNameRoute =
  ApiPublicTelegramImageNameRouteImport.update({
    id: '/api/public/telegram/image/$name',
    path: '/api/public/telegram/image/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/telegram/is-admin': typeof ApiPublicTelegramIsAdminRoute
  '/api/public/telegram/session': typeof ApiPublicTelegramSessionRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/verify-access': typeof ApiPublicTelegramVerifyAccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/image/$name': typeof ApiPublicTelegramImageNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/telegram/is-admin': typeof ApiPublicTelegramIsAdminRoute
  '/api/public/telegram/session': typeof ApiPublicTelegramSessionRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/verify-access': typeof ApiPublicTelegramVerifyAccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/image/$name': typeof ApiPublicTelegramImageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/telegram/is-admin': typeof ApiPublicTelegramIsAdminRoute
  '/api/public/telegram/session': typeof ApiPublicTelegramSessionRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/verify-access': typeof ApiPublicTelegramVerifyAccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram/image/$name': typeof ApiPublicTelegramImageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/telegram/is-admin'
    | '/api/public/telegram/session'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/verify-access'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/image/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/telegram/is-admin'
    | '/api/public/telegram/session'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/verify-access'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/image/$name'
  id:
    | '__root__'
    | '/'
    | '/api/public/telegram/is-admin'
    | '/api/public/telegram/session'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/verify-access'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram/image/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicTelegramIsAdminRoute: typeof ApiPublicTelegramIsAdminRoute
  ApiPublicTelegramSessionRoute: typeof ApiPublicTelegramSessionRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramVerifyAccessRoute: typeof ApiPublicTelegramVerifyAccessRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelegramImageNameRoute: typeof ApiPublicTelegramImageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/is-admin': {
      id: '/api/public/telegram/is-admin'
      path: '/api/public/telegram/is-admin'
      fullPath: '/api/public/telegram/is-admin'
      preLoaderRoute: typeof ApiPublicTelegramIsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/session': {
      id: '/api/public/telegram/session'
      path: '/api/public/telegram/session'
      fullPath: '/api/public/telegram/session'
      preLoaderRoute: typeof ApiPublicTelegramSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/verify-access': {
      id: '/api/public/telegram/verify-access'
      path: '/api/public/telegram/verify-access'
      fullPath: '/api/public/telegram/verify-access'
      preLoaderRoute: typeof ApiPublicTelegramVerifyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/image/$name': {
      id: '/api/public/telegram/image/$name'
      path: '/api/public/telegram/image/$name'
      fullPath: '/api/public/telegram/image/$name'
      preLoaderRoute: typeof ApiPublicTelegramImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicTelegramIsAdminRoute: ApiPublicTelegramIsAdminRoute,
  ApiPublicTelegramSessionRoute: ApiPublicTelegramSessionRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramVerifyAccessRoute: ApiPublicTelegramVerifyAccessRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelegramImageNameRoute: ApiPublicTelegramImageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
